all:
  children:
    ubuntu_vms:
      hosts:
        ubuntu-1:
          ansible_host: 
        ubuntu-2:
          ansible_host: 10.5.0.150
      vars:
        ansible_user: ansible
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519_ansible
        ansible_python_interpreter: /usr/bin/python3